name: FTP Deploy

on:
  push:
    branches:
      - master  # Triggers the workflow on push to the 'master' branch

jobs:
  ftp-deploy:
    name: Deploy to FTP Server
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Upload files to FTP server
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: 'ftp.rscollectionbd.com'
          username: 'StudyTown@studytown.rscollectionbd.com'
          password: '0=X-3#YS@p6U'
          port: 21
          protocol: ftps  # Use 'ftp' if the server doesn't support FTPS
          local-dir: ./   # Upload all files from the root directory of the repo
          server-dir: /path/to/your/project/  # Change to the correct path on your server
          exclude: |
            .git*              # Exclude .git directory
            .github*           # Exclude GitHub actions/workflows
            node_modules/      # Exclude node_modules (if using npm)
            vendor/            # Exclude vendor directory if you run Composer install on the server
            storage/logs/      # Exclude logs
            storage/debugbar/  # Exclude debugbar files
          exclude-method: ignore  # Ignore these files instead of deleting them from the server
